const actiontypes = Object.freeze({
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

    USER_LOGOUT: 'USER_LOGOUT',

    ADMIN_FETCH_BANNER_SUCCESS: 'ADMIN_FETCH_BANNER_SUCCESS',
    ADMIN_FETCH_BANNER_FAIL: 'ADMIN_FETCH_BANNER_FAIL',

    ADMIN_FETCH_TYPE_PRODUCT_SUCCESS: 'ADMIN_FETCH_TYPE_PRODUCT_SUCCESS',
    ADMIN_FETCH_TYPE_PRODUCT_FAIL: 'ADMIN_FETCH_TYPE_PRODUCT_FAIL',

    ADMIN_FETCH_PRODUCT_DISPLAY_SUCCESS: 'ADMIN_FETCH_PRODUCT_DISPLAY_SUCCESS',
    ADMIN_FETCH_PRODUCT_DISPLAY_FAIL: 'ADMIN_FETCH_PRODUCT_DISPLAY_FAIL',


    ADMIN_FETCH_PRODUCT_CHARACTER_SUCCESS: 'ADMIN_FETCH_PRODUCT_CHARACTER_SUCCESS',
    ADMIN_FETCH_PRODUCT_CHARACTER_FAIL: 'ADMIN_FETCH_PRODUCT_CHARACTER_FAIL',


    ADMIN_FETCH_PRODUCT_ANIME_SUCCESS: 'ADMIN_FETCH_PRODUCT_ANIME_SUCCESS',
    ADMIN_FETCH_PRODUCT_ANIME_FAIL: 'ADMIN_FETCH_PRODUCT_ANIME_FAIL',

    FETCH_ALL_PRODUCT_SUCCESS: 'FETCH_ALL_PRODUCT_SUCCESS',
    FETCH_ALL_PRODUCT_FAIL: 'FETCH_ALL_PRODUCT_FAIL',


    FETCH_DATA_ALLCODES_GENDER_SUCCESS: 'FETCH_DATA_ALLCODES_GENDER_SUCCESS',
    FETCH_DATA_ALLCODES_GENDER_FAIL: 'FETCH_DATA_ALLCODES_GENDER_FAIL',

    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAIL: ' FETCH_ALL_USER_FAIL',
})
export default actiontypes