const actiontypes = Object.freeze({
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

    USER_LOGOUT: 'USER_LOGOUT',

    ADMIN_FETCH_BANNER_SUCCESS: 'ADMIN_FETCH_BANNER_SUCCESS',
    ADMIN_FETCH_BANNER_FAIL: 'ADMIN_FETCH_BANNER_FAIL',

    ADMIN_FETCH_TYPE_PRODUCT_SUCCESS: 'ADMIN_FETCH_TYPE_PRODUCT_SUCCESS',
    ADMIN_FETCH_TYPE_PRODUCT_FAIL: 'ADMIN_FETCH_TYPE_PRODUCT_FAIL',

    ADMIN_CREATE_PRODUCT_SUCCESS: 'ADMIN_CREATE_PRODUCT_SUCCESS',
    ADMIN_CREATE_PRODUCT_FAIL: 'ADMIN_CREATE_PRODUCT_FAIL'

})
export default actiontypes